
### definitions ###

# default/library definitions
include $(FINESS)/lib/1d/Makefile.defs

# overridden library objects
#
DFluxFunc             = DFluxFunc
D2FluxFunc            = D2FluxFunc

#DogSolveUser           = $(FINESS)/lib/1d/DogSolveTDRK

# Experimental new method that uses WENO *differentiation* on the interior of
# the time-integrated flux function.
#ConstructIntegratedF    = ConstructIntegratedF

# place to add object modules
#
#ALL_OBJECTS = $(COMMON_OBJECTS) ...
#ALL_SOURCES = $(COMMON_SOURCES) ...

### targets ###

include $(FINESS)/lib/1d/Makefile.targets

### DO NOT remove this line - make depends on it ###
