
### definitions ###

# default/library definitions
include $(FINESS)/lib/2d/Makefile.defs

# overridden library objects
#
#Output               = Output
DFluxFunc             = DFluxFunc
D2FluxFunc            = D2FluxFunc

# place to add object modules
#
ALL_OBJECTS = \
$(COMMON_OBJECTS) \

ALL_SOURCES = \
$(COMMON_SOURCES) \

### targets ###

include $(FINESS)/lib/2d/Makefile.targets

### DO NOT remove this line - make depends on it ###
