### definitions ###

# default/library definitions
include $(FINESS)/lib/1d/Makefile.defs

# overridden library objects
#
InitApp     =  InitApp
#AfterQinit  =  AfterQinit

# place to add object modules
#
ALL_OBJECTS = $(COMMON_OBJECTS) 

ALL_SOURCES = $(COMMON_SOURCES)
### targets ###

include $(FINESS)/lib/1d/Makefile.targets

### DO NOT remove this line - make depends on it ###
