### definitions ###

# default/library definitions
include $(FINESS)/lib/Makefile.defs

### targets ###

lib: $(ALL_OBJECTS)

include $(FINESS)/lib/Makefile.targets

### DO NOT remove this line - make depends on it ###
