# MAIN EXECUTABLE - NOTE, I found that SHARED_OBJECTS needs to be included
# LAST in order to get the code to compile with PAPI counters! -DS
finess.exe: $(ALL_OBJECTS) $(ALL_SOURCES)
	$(LINK) $(ALL_OBJECTS) $(SHARED_OBJECTS) -o $(EXECUTABLE)

include $(FINESS)/lib/sys/Makefile.targets

cleanout:
	rm -rf output

cleanall: cleanallo
	rm -f $(CLEANALL_FILES)
	rm -rf $(CLEANALL_DIRS)

run:
	time ./$(EXECUTABLE) -o $(output)


$(INIPARAMS_H): $(INIPARSER_H) 
	python $(GENERATE_INIPARAMS_PY)

$(INIPARAMS_CPP): $(INIPARSER_H) $(INIPARAMS_H)
	@true

generate_iniparams: $(GENERATE_INIPARAMS_PY)


