
finess.exe: $(ALL_OBJECTS) $(ALL_SOURCES)
	$(CXX) $(FFLAGS) $(ALL_OBJECTS) -o $(EXECUTABLE)

# does anyone use this any more?
# you can also do this using: make -s ls | xargs cat > dog2program.cpp
#program : $(ALL_SOURCES)
#	cat $(ALL_SOURCES) > dog2program.cpp

include $(FINESS)/lib/sys/Makefile.targets

cleanout:
	rm -rf output

cleanall: cleanallo
	rm -f $(CLEANALL_FILES)
	rm -rf $(CLEANALL_DIRS)

run:
	time ./$(EXECUTABLE) -o $(output)


$(INIPARAMS_H): $(INIPARSER_H) 
	python $(GENERATE_INIPARAMS_PY)

$(INIPARAMS_CPP): $(INIPARSER_H) $(INIPARAMS_H)
	@true

generate_iniparams: $(GENERATE_INIPARAMS_PY)


