# This file is used for system specific configurations.  The most common use
# of this file is to a) select your compiler, and b) decide optimization flags
# and whether or not to turn on OpenMP threads.
#
# Each application has its own personal "Makefile", that points to common
# objects found in the main library.  Common items are first defined in the
# following Makefiles:
#
#       $FINESS/lib/Makefile.defs
#       $FINESS/lib/Makefile.targets
#       $FINESS/lib/[1-3]d/Makefile.defs        # For 1,2 and 3D code
#       $FINESS/lib/[1-3]d/Makefile.targets     # For 1,2 and 3D code
#
# An individual Makefile can relink these subroutines as necessary.

# Choose your compiler here. (On Macs, I use g++-4.9, installed via homebrew -DS)
#CXX = g++-4.9
CXX = g++

# -E: show preprocessor output
#
# The most commonly used flags are:
#
#   -pg                 : instrument for profiling (see gprof)
#   -ggdb               : produce debugging information (see gdb)
#   -fopenmp            : take #pragma loops
#   -O4                 : use level-4 optimization
#   -DCHECK_BOUNDS      : use bounds-checking in tensor class (expensive)
#   -DMAX_DEBUG_LEVEL=3 : allow level-3 debug
#   $(FAST_MATH)        : sacrifice IEEE compliance for speed

# A few examples of alternative flags that can be used are
#
#  -ffast-math : sacrifice IEEE compliance for speed
#    (sets -fno-math-errno, -funsafe-math-optimizations,
#    -fno-trapping-math, -ffinite-math-only, -fno-rounding-math,
#    -fno-signaling-nans and fcx-limited-range.)
#
#  -fno-finite-math-only : so we can still test for NAN
#
#  -funsafe-math-optimizations : using this flag (instead of --ffast-math)
#     seems to give most of the benefit of -ffast-math
#     (e.g. "/" = "*reciprocal")
#
#FAST_MATH = -ffast-math -fno-finite-math-only

# serial code with optimizer turned on:
# FFLAGS = -O4

# threaded code with the optimizer turned on:
FFLAGS = -O4 -fopenmp

COMPILE = time $(CXX) $(FFLAGS) -c $(INCLUDE_LIBS)

# Can be used to generate ctags files for navigating code.
# See (http://ctags.sourceforge.net) for more details
CTAGS = ctags --extra=+q

## 
# I don't know where these commands get used ... -DS
#
# -show: display g++ commands that would be executed
# -echo: show *all* commands and execute them
