### definitions ###

# default/library definitions
include $(FINESS)/lib/2d/Makefile.defs

# overridden library objects
#
#AfterQinit  =  AfterQinit
InitApp      = InitApp
DFluxFunc    = DFluxFunc
D2FluxFunc   = D2FluxFunc

ALL_OBJECTS = $(COMMON_OBJECTS) \
EulerParams.o \

ALL_SOURCES = $(COMMON_SOURCES) \
EulerParams.cpp \

### targets ###

include $(FINESS)/lib/2d/Makefile.targets

### DO NOT remove this line - make depends on it ###
